# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Node.js CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
    - uses: actions/checkout@v2
      with:
          fetch-depth: 2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: set environment variables
      uses: allenevans/set-env@v1.0.0
      with:
          GIT_USER: ${{ secrets.WEB_GITLAB_USER }}
          GIT_TOKEN: ${{ secrets.WEB_GITLAB_TOKEN }}
          GIT_MAIL: ${{ secrets.USER_MAIL }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_PORT: ${{ secrets.DB_PORT }}
          DB_SERVER: ${{ secrets.DB_SERVER }}
          DB_USER: ${{ secrets.DB_USER }}
          DB_NAME: ${{ secrets.DB_NAME }}
    
    - name: Install
      run: npm i
    
    - name: Get changed files
      run: |
          git diff --name-only HEAD^ HEAD
        
    - name: Publish
      run: npm run publish
      env:
         GIT_USER: ${{ secrets.WEB_GITLAB_USER }}
         GIT_TOKEN: ${{ secrets.WEB_GITLAB_TOKEN }}
         GIT_MAIL: ${{ secrets.USER_MAIL }}
         DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
         DB_PORT: ${{ secrets.DB_PORT }}
         DB_SERVER: ${{ secrets.DB_SERVER }}
         DB_USER: ${{ secrets.DB_USER }}
         DB_NAME: ${{ secrets.DB_NAME }}
